spring.config.import=optional:file:.env[.properties]

server.port=${SERVER_PORT:8081}

spring.application.name=commercial-service

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver


spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}
spring.rabbitmq.virtual-host=/
rabbitmq.dynamic=false
# Evitar bucles infinitos en errores
spring.rabbitmq.listener.simple.default-requeue-rejected=false

rabbitmq.exchange.commercial=${RABBITMQ_EXCHANGE_COMMERCIAL:commercial.exchange}

sales.patch.request.exchange=${RABBITMQ_EXCHANGE_SALES_PATCH_REQUEST:sales.patch.request.exchange}
sales.patch.request.queue=${RABBITMQ_QUEUE_SALES_PATCH_REQUEST:sales.patch.request.queue}
sales.patch.request.routingKey=${RABBITMQ_ROUTING_KEY_SALES_PATCH_REQUEST:sales.patch.request}

sales.create.response.queue=${RABBITMQ_QUEUE_SALES_CREATE_RESPONSE:sales.create.response.queue}
sales.update.response.queue=${RABBITMQ_QUEUE_SALES_UPDATE_RESPONSE:sales.update.response.queue}
sales.delete.response.queue=${RABBITMQ_QUEUE_SALES_DELETE_RESPONSE:sales.delete.response.queue}

rabbitmq.queue.purchase=${RABBITMQ_QUEUE_PURCHASE:purchase.queue}
rabbitmq.routing-key.purchase=${RABBITMQ_ROUTING_KEY_PURCHASE:purchase.received}
rabbitmq.exchange.dlx=${RABBITMQ_EXCHANGE_DLX:commercial.dlx}
rabbitmq.queue.purchase.dlq=${RABBITMQ_QUEUE_PURCHASE_DLQ:purchase.queue.dlq}
rabbitmq.routing-key.purchase.dlq=${RABBITMQ_ROUTING_KEY_PURCHASE_DLQ:purchase.failed}

rabbitmq.exchange.inventory=${RABBITMQ_EXCHANGE_PRODUCT:product.exchange}
rabbitmq.routing-key.inventory.stock=${RABBITMQ_ROUTING_KEY_PRODUCT_STOCK:product.stock.updated}

# Table CRUD
rabbitmq.queue.table-crud=${RABBITMQ_QUEUE_TABLE_CRUD:table.crud.queue}
rabbitmq.routing-key.table-crud=${RABBITMQ_ROUTING_KEY_TABLE_CRUD:table.crud.routing-key}
# Table Session
rabbitmq.queue.table-session=${RABBITMQ_QUEUE_TABLE_SESSION:table.session.queue}
rabbitmq.routing-key.table-session=${RABBITMQ_ROUTING_KEY_TABLE_SESSION:table.session.routing-key}
# Table Reservation
rabbitmq.queue.table-reservation=${RABBITMQ_QUEUE_TABLE_RESERVATION:table.reservation.queue}
rabbitmq.routing-key.table-reservation=${RABBITMQ_ROUTING_KEY_TABLE_RESERVATION:table.reservation.routing-key}
# Table Session Open Request
rabbitmq.exchange.table-session-open=${RABBITMQ_EXCHANGE_TABLE_SESSION_OPEN:table.session.open.request.exchange}
rabbitmq.queue.table-session-open=${RABBITMQ_QUEUE_TABLE_SESSION_OPEN:table.session.open.request.queue}
rabbitmq.routing-key.table-session-open=${RABBITMQ_ROUTING_KEY_TABLE_SESSION_OPEN:table.session.open.request}

# Discount
rabbitmq.queue.discount=${RABBITMQ_QUEUE_DISCOUNT:discount.queue}
rabbitmq.routing-key.discount=${RABBITMQ_ROUTING_KEY_DISCOUNT:discount.events}
# CustomerDiscount
rabbitmq.queue.customer-discount=${RABBITMQ_QUEUE_CUSTOMER_DISCOUNT:customer.discount.queue}
rabbitmq.routing-key.customer-discount=${RABBITMQ_ROUTING_KEY_CUSTOMER_DISCOUNT:customer.discount.events}

# Seller
rabbitmq.queue.seller=${RABBITMQ_QUEUE_SELLER:seller.queue}
rabbitmq.routing-key.seller=${RABBITMQ_ROUTING_KEY_SELLER:seller.events}