spring.application.name=commercial-service

sales.patch.request.exchange=sales.patch.request.exchange
sales.patch.request.queue=sales.patch.request.queue
sales.patch.request.routingKey=sales.patch.request
