spring.config.import=optional:file:.env[.properties]

spring.application.name=commercial-service
server.port=${SERVER_PORT:8081}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}

sales.patch.request.exchange=${RABBITMQ_EXCHANGE_SALES_PATCH_REQUEST:sales.patch.request.exchange}
sales.patch.request.queue=${RABBITMQ_QUEUE_SALES_PATCH_REQUEST:sales.patch.request.queue}
sales.patch.request.routingKey=${RABBITMQ_ROUTING_KEY_SALES_PATCH_REQUEST:sales.patch.request}